some comments in model
Krysset/TDA367-Projektgrupp-16 pull request #112
Opened 2022-10-13 12:01 UTC by CurryNRice

2022-10-14 07:35 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/overworld/OverworldModel.java
> +import com.g16.feyrune.model.overworld.map.Map;
Why is this import added?

2022-10-18 11:10 UTC, x183 approved these changes
Looks good

2022-10-18 11:15 UTC, Supergamer1337 requested changes

2022-10-18 11:26 UTC, Supergamer1337 approved these changes
I fixed the thing, someone else look

2022-10-18 11:28 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/overworld/MovementHandler.java
> + * This class is responsible for transelateing an inpout direction from the controller to a new position for the player
typo

2022-10-18 11:28 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/overworld/MovementHandler.java
> +     * Chekes if player is allowed to move accoring to time passed
typo

2022-10-18 11:28 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/overworld/MovementHandler.java
> +     * Chekes if player is allowed to move accoring to time passed
2x

2022-10-18 11:29 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/overworld/MovementHandler.java
> + * This class is responsible for transelateing an inpout direction from the controller to a new position for the player
2x

2022-10-18 11:30 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/StateHandler.java
> + * and witch part of the model that should get polled
typo 2x on witch

2022-10-18 11:33 UTC, x183 approved these changes
100% more sexy now

2022-10-18 11:33 UTC, Krysset approved these changes
Looks good very happy 😎

2022-10-18 11:33 UTC, merged