Refactor model
Krysset/TDA367-Projektgrupp-16 pull request #59
Opened 2022-09-22 08:42 UTC by lutches

refactored model according to the new uml-diagram

2022-09-22 09:05 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/Model.java
> +    public Model() {
Borde inte model ha en constructor där den tar in en spelare? Annars behöver vi en funktion för getPlayer() så att CombatModel får access till spelarens data. Eller hanterar vi det annorlunda nu?

2022-09-22 09:13 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/combat/CombatModel.java
> +        while(true) {
När går vi ur while(true) loopen? Ser ingen break

2022-09-22 09:22 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/EnemyCreature.java
> +        return null;
Borde vi inte kunna delegera funktionerna till interfacen redan? Spelar ju inte roll än om dom är implementerade eller inte? Menar detta för get funktionerna under med

2022-09-22 09:22 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/PlayerCreature.java
> +        return null;
Borde väl kunna delegera till ICreature här med?

2022-09-22 09:23 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/PlayerCreature.java
> +        return null;
Insert // TODO kanske?

2022-09-22 09:25 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/creature/BaseCreature.java
> +        return dead;
Borde inte denna kunna returnera en bool utefter hp? Så slipper vi en massa extra grejer

2022-09-22 09:29 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/Model.java
> +    public Model() {
Me dum dum

2022-09-22 10:06 UTC, CurryNRice commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/EnemyCreature.java
> +        creature.takeDamage(damage);
finns i take damage

2022-09-22 11:13 UTC, Krysset commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/EnemyCreature.java
> +        creature.takeDamage(damage);
true tänkte inte på det

2022-09-23 06:39 UTC, x183 requested changes
See comments

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/combat/actions/IMove.java
> +public interface IMove {
IMove är ett lite tvetydigt namn

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/EnemyCreature.java
> +    private IMove createNewMoveUsingPower(IMove move) {
Horriffic name

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/EnemyCreature.java
> +        return null;
Please return an action instead of null

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/EnemyCreature.java
> +        return null;
Please don't return null

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/PlayerCreature.java
> +        return null;
please no null :scream:

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/combat/creatures/PlayerCreature.java
> +        return null;
still null :scream:

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/creature/BaseCreature.java
> +    private boolean dead = false;
should be isDead?

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/creature/BaseCreature.java
> +    private void die() {
DIE!!!!!
![image](https://user-images.githubusercontent.com/55193662/191902216-919a0b17-756a-4a54-b34c-232c4e1e2005.png)

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/model/overworld/MovementHandler.java
>      private long moveFrequency = 500;
Might be nice to move this to config file?

2022-09-23 06:39 UTC, x183 commented on core/src/main/java/com/g16/feyrune/view/player/PlayerRenderer.java
> +        playerPos = new Vector2(player.getCoordinates().x, player.getCoordinates().y);
Why is this a Vector2 and not a Point?

2022-09-23 08:25 UTC, closed without merging